version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./relief/:/usr/src/app/
      - ./relief.sqlite:/usr/src/app/relief.sqlite:rw
    env_file:
      - ./.env.dev
    depends_on:
      - redis
  huey:
    build:
      context: ./
      dockerfile: Dockerfile
    command: python manage.py run_huey
    volumes:
      - ./relief/:/usr/src/app/
      - ./relief.sqlite:/usr/src/app/relief.sqlite:rw
    env_file:
      - ./.env.dev
    depends_on:
      - redis
  redis:
    image: redis:alpine
    restart: "no"
    hostname: redis
    ports:
      - 6379:6379