version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/local/python/Dockerfile
    command: python /code/relief/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .dev_env
    volumes:
      - .:/code
  db:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .dev_env
    volumes:
    - ./seed:/docker-entrypoint-initdb.d/
