version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn relief.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - ./relief/:/home/app/
      - static_volume:/home/app/relief/staticfiles
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/relief/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume: