from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from . import api

urlpatterns = [
    path('api/customers/', api.CustomerList.as_view(), name='customer_list'),
    path('api/customers/sync/', api.customer_sync, name='customer_sync'),
    path('api/products/', api.ProductList.as_view(), name='product_list'),
    path('api/customers/freshbooks/', api.get_freshbooks_clients, name='freshbooks_client_list'),
    path('api/customers/freshbooks/import/', api.get_freshbooks_import_clients, name='freshbooks_import_client_list'),
    path('api/customers/freshbooks/import/create/', api.import_freshbooks_clients, name='freshbooks_import_client'),
    path('api/products/freshbooks/', api.get_freshbooks_products, name='freshbooks_product_list'),
    path('api/products/freshbooks/import/', api.get_freshbooks_import_products, name='freshbooks_import_product_list'),
    path('api/products/freshbooks/import/create/', api.import_freshbooks_products, name='freshbooks_import_product'),    
    path('api/products/<int:pk>/', api.product_detail, name='product_detail'),
    path('api/quote/', api.CustomerProductCreate.as_view(), name='customerproduct_create'),
    path('api/quotes/', api.get_all_quotes, name='all_quotes'),
    path('api/express/import/', api.bulk_import_orders, name='bulk_import_orders'),
    path('api/orderitems/', api.get_filter_orderitem_rows, name='orderitems_filter'),
    path('api/taxes/', api.get_all_taxes, name='taxes_list'),
    path('api/invoice/create/', api.create_invoice, name='invoice_create'),
    path('api/groups/all/', api.GroupList.as_view(), name='list_all_groups'),
    path('api/group/create/', api.group_create, name='group_create'),
    path('api/group/update/', api.update_grouping, name='group_update'),
    path('api/customer/link/', api.link_customer, name='link_customers'),
    path('api/product/link/', api.link_product, name='link_products'),
    path('api/orderitem/<int:pk>/delete/', api.orderitem_delete, name='orderitem_delete'),
    path('api/invoices/', api.InvoiceList.as_view(), name='invoice_list'),
    path('api/invoices/delete/<int:pk>/', api.hard_delete_invoice, name='invoice_delete'),
    path('api/invoices/unlink/<int:pk>/', api.unlink_invoice, name='invoice_unlink'),
    path('api/invoices/<int:pk>/', api.InvoiceDetail.as_view(), name='invoice_detail'),
    path('api/invoices/<int:pk>/update/', api.invoice_update, name='invoice_update'),
    path('api/invoices/sync/', api.invoice_sync, name='invoice_sync'),
    path('api/orderitem/<int:pk>/update/', api.OrderItemUpdate.as_view(), name='orderitem_update'),
    path('api/quote/<int:pk>/update/', api.CustomerProductUpdate.as_view(), name='customerproduct_update'),
    path('api/customers/<int:pk>/products/', api.CustomerProductList.as_view(), name='customerproduct_list'),
    path('api/customerproduct/<int:pk>/', api.CustomerProductDetail.as_view(), name='customerproduct_detail'),
    path('api/customerproduct/<int:pk>/delete/', api.customerproduct_delete, name='customerproduct_delete'),
    path('api/customers/<int:pk>/customerproduct/arrangement/', api.customerproduct_arrangement, name='customerproduct_arrangement'),
    path('api/customers/<int:pk>/routes/', api.CustomerRouteList.as_view(), name='customerroute_list'),
    path('api/trips/', api.TripList.as_view(), name='trip_list'),
    path('api/trips/<int:pk>/', api.TripDetail.as_view(), name='api_trip_detail'),
    path('api/trip/create/', api.TripCreate.as_view(), name='trip_create'),
    path('api/trip/update/<int:pk>/', api.TripUpdate.as_view(), name='trip_update'),
    path('api/trip/<int:pk>/delete/', api.TripDelete.as_view(), name='trip_delete'),
    path('api/trip/<int:pk>/duplicate/', api.TripDuplicate.as_view(), name='trip_duplicate'),
    path('api/trip/<int:pk>/packingsum/', api.trip_packing_sum, name='trip_packing_sum'),
    path('api/trips/<int:pk>/detail/routes/', api.TripRouteList.as_view(), name='trip_route_list'),
    path('api/trips/<int:pk>/detail/routes/add/', api.TripRouteCreate.as_view(), name='trip_route_create'),
    path('api/routes/<int:pk>/delete/', api.RouteDelete.as_view(), name='route_delete'),
    path('api/routes/<int:pk>/update/', api.RouteUpdate.as_view(), name='route_update'),
    path('api/routes/<int:pk>/', api.RouteDetail.as_view(), name='route_detail'),
    path('api/orderitem/<int:pk>/', api.OrderItemDetail.as_view(), name='orderitem_detail'),
    path('api/trips/<int:pk>/routes/arrange/', api.route_arrange, name='route_arrange'),
]

urlpatterns = format_suffix_patterns(urlpatterns)
