# Generated by Django 2.0 on 2019-07-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='term',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
