# Generated by Django 2.2 on 2020-10-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='freshbooks_tax_1',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
