# Generated by Django 2.0 on 2018-07-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_year',
            field=models.IntegerField(null=True),
        ),
    ]
