# Generated by Django 2.0 on 2018-07-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_auto_20180710_0002'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('invoice_year', 'invoice_number')},
        ),
    ]
