# Generated by Django 2.2 on 2020-10-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_auto_20201022_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6),
        ),
    ]
