# Generated by Django 2.0 on 2019-07-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_auto_20190714_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gst',
            field=models.DecimalField(decimal_places=0, default=7, max_digits=1),
        ),
    ]
