# Generated by Django 2.0 on 2018-07-11 16:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_auto_20180710_0011'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='method',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='method',
            name='orderitem',
        ),
        migrations.RemoveField(
            model_name='method',
            name='packing',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='packing',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='Method',
        ),
        migrations.DeleteModel(
            name='Packing',
        ),
    ]
