# Generated by Django 2.0 on 2019-07-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_auto_20190714_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='term',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
