# Generated by Django 2.2 on 2020-11-04 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_product_unit_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customerproduct',
            unique_together={('customer', 'product', 'quote_price')},
        ),
    ]
