# Generated by Django 2.0 on 2018-07-18 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_auto_20180712_0032'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('index', 'trip')},
        ),
    ]
