# Generated by Django 2.2 on 2020-11-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_auto_20201104_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='do_number',
            field=models.CharField(max_length=8),
        ),
    ]
