# Generated by Django 2.0 on 2019-07-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_auto_20190714_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='do_number',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
