# Generated by Django 2.0 on 2018-07-19 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_auto_20180719_0129'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='route',
            unique_together=set(),
        ),
    ]
