# Generated by Django 2.2 on 2020-11-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_auto_20201104_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='freshbooks_account_id',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='freshbooks_client_id',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
