# Generated by Django 2.0 on 2018-07-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_auto_20180719_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gst',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='gst',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=2),
        ),
    ]
