# Generated by Django 2.0 on 2019-10-28 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_customergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customergroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pos.CustomerGroup'),
        ),
    ]
