# Generated by Django 2.0 on 2019-11-09 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_customer_customergroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customergroup',
        ),
        migrations.RemoveField(
            model_name='customergroup',
            name='name',
        ),
        migrations.AddField(
            model_name='customergroup',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pos.Customer'),
        ),
        migrations.AddField(
            model_name='customergroup',
            name='index',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customergroup',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pos.Group'),
        ),
    ]
