# Generated by Django 2.2 on 2020-11-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_auto_20201107_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['route__date']},
        ),
    ]
