# Generated by Django 2.2 on 2020-11-20 18:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_auto_20201117_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproduct',
            name='quote_price',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
