# Generated by Django 2.0 on 2019-12-16 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_auto_20191109_1728'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customergroup',
            unique_together={('group', 'index')},
        ),
    ]
