# Generated by Django 2.0 on 2020-02-02 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_auto_20191216_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 2, 2)),
        ),
        migrations.AlterUniqueTogether(
            name='customerproduct',
            unique_together=set(),
        ),
    ]
