# Generated by Django 2.2 on 2020-11-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_auto_20201120_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
