# Generated by Django 2.0 on 2020-04-16 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_auto_20200202_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproduct',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 4, 16)),
        ),
    ]
