# Generated by Django 2.2 on 2020-11-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_customerproduct_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('invoice_number', 'customer')},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_year',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='original_total',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='start_date',
        ),
    ]
