# Generated by Django 2.0 on 2020-04-16 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_auto_20200416_1109'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customergroup',
            unique_together=set(),
        ),
    ]
