# Generated by Django 2.2 on 2020-11-27 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_auto_20201127_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='invoice',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.Invoice'),
        ),
    ]
