# Generated by Django 2.0 on 2020-04-30 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_auto_20200416_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='final_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='route',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customerproduct',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 4, 30)),
        ),
    ]
