# Generated by Django 2.2 on 2020-12-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_auto_20201127_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['invoice_number']},
        ),
        migrations.AddField(
            model_name='customer',
            name='pivot_invoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pivot',
            field=models.BooleanField(default=False),
        ),
    ]
