# Generated by Django 2.0 on 2020-05-01 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_auto_20200430_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproduct',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 5, 1)),
        ),
    ]
