# Generated by Django 2.0 on 2020-05-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_auto_20200501_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproduct',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
