# Generated by Django 2.0 on 2020-05-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_auto_20200501_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
