# Generated by Django 2.2 on 2020-12-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_auto_20201226_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
