# Generated by Django 2.2 on 2020-12-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_auto_20201226_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='freshbooks_account_id',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='freshbooks_item_id',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
