# Generated by Django 2.0 on 2020-05-27 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_auto_20200507_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='final_quantity',
        ),
    ]
