# Generated by Django 2.0 on 2020-05-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_remove_orderitem_final_quantity'),
    ]

    def create_customerproduct_index(apps, schema_editor):
        # We get the model from the versioned app registry;
        # if we directly import it, it'll be the wrong version
        Customer = apps.get_model("pos", "Customer")
        for customer in Customer.objects.all():
            index = 0
            customerproducts = customer.customerproduct_set.all()
            for cp in customerproducts:
                cp.index = index
                cp.save()
                index += 1


    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='index',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.RunPython(create_customerproduct_index)
    ]
