# Generated by Django 2.2 on 2021-01-03 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_auto_20201228_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customergroup',
            options={'ordering': ['customer__name']},
        ),
    ]
