# Generated by Django 2.0 on 2020-05-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_customerproduct_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproduct',
            name='index',
            field=models.PositiveIntegerField(),
        ),
    ]
