# Generated by Django 2.2 on 2021-01-03 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_auto_20210103_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='customergroup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
