# Generated by Django 2.0 on 2020-06-13 05:30

from django.db import migrations, models
import uuid


def gen_uuid(apps, schema_editor):
    Customer = apps.get_model('pos', 'Customer')
    for row in Customer.objects.all():
        row.url = uuid.uuid4()
        row.save(update_fields=['url'])


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0019_auto_20200528_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerproduct',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['customerproduct__index']},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['index']},
        ),
        migrations.AddField(
            model_name='customer',
            name='url',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(gen_uuid),
    ]
