# Generated by Django 2.2 on 2021-01-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0019_auto_20210103_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='invoice',
            name='po_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
