# Generated by Django 2.2 on 2021-01-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0020_auto_20210106_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='freshbooks_account_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='freshbooks_invoice_id',
            field=models.TextField(null=True),
        ),
    ]
