# Generated by Django 2.0 on 2020-06-13 05:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0020_auto_20200613_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='url',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
