# Generated by Django 2.2 on 2021-01-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0021_auto_20210106_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_created',
            field=models.DateField(null=True),
        ),
    ]
