# Generated by Django 2.2 on 2021-04-21 07:48

import datetime
from django.db import migrations, models

def save_sort_order(apps, schema_editor):
    Customer = apps.get_model("pos", "Customer")
    for customer in Customer.objects.all():
        customerproducts = customer.customerproduct_set.all()
        for i in range(len(customerproducts)):
            customerproduct = customerproducts[i]
            customerproduct.sort_order = i
            customerproduct.save()

class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0022_invoice_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerproduct',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['pk']},
        ),
        migrations.RemoveField(
            model_name='trip',
            name='date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='packaging_methods',
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='sort_order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='po_number',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='route',
            name='do_number',
            field=models.CharField(max_length=128),
        ),
        migrations.RunPython(save_sort_order, migrations.RunPython.noop),
    ]
