# Generated by Django 4.0 on 2021-12-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0023_auto_20210421_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='download_prefix',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='download_suffix',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='to_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='to_fax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='to_print',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='to_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='packing',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
