# Generated by Django 4.0 on 2022-01-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0024_customer_download_prefix_customer_download_suffix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='do_image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
