# Generated by Django 4.0 on 2022-01-20 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0025_route_do_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='trip',
        ),
    ]
