# Generated by Django 4.0 on 2022-01-20 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0026_remove_route_trip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
