# Generated by Django 4.0 on 2022-01-20 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0027_delete_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='do_image',
        ),
    ]
