# Generated by Django 4.0 on 2022-12-31 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id'),
        ('pos', '0028_remove_route_do_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='freshbooks_account_id',
            field=models.CharField(default='wo1Oj', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
