# Generated by Django 4.0 on 2025-06-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0030_auto_20230131_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gst',
            field=models.DecimalField(decimal_places=0, default=9, max_digits=1),
        ),
    ]
