# Generated by Django 4.0 on 2025-06-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0031_alter_customer_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='huey_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.TextField(null=True),
        ),
    ]
