# Generated by Django 4.0 on 2025-07-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0032_invoice_huey_task_id_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='currency',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
