# Generated by Django 4.0 on 2025-07-16 13:04

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0033_customer_currency'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('objects_all_companies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='customergroup',
            managers=[
                ('objects_all_companies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='customerproduct',
            managers=[
                ('objects_all_companies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='group',
            managers=[
                ('objects_all_companies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='invoice',
            managers=[
                ('objects_all_companies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='orderitem',
            managers=[
                ('objects_all_companies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('objects_all_companies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='route',
            managers=[
                ('objects_all_companies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pos.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customergroup',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pos.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pos.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pos.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pos.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pos.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pos.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pos.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='business_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='fax_no',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='postal_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='tel_no',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
