# Generated by Django 4.0 on 2025-06-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='freshbooks_access_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='FreshBooks OAuth Token'),
        ),
        migrations.AddField(
            model_name='user',
            name='freshbooks_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='FreshBooks OAuth Refresh Token'),
        ),
        migrations.AddField(
            model_name='user',
            name='freshbooks_token_expires',
            field=models.IntegerField(blank=True, null=True, verbose_name='FreshBooks OAuth Token Expiration'),
        ),
    ]
