# Generated by Django 4.0 on 2025-07-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0034_alter_customer_managers_alter_customergroup_managers_and_more'),
        ('users', '0004_user_freshbooks_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='companies',
            field=models.ManyToManyField(blank=True, null=True, related_name='companies', to='pos.Company'),
        ),
    ]
