FROM python:3.6
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
COPY . /home/Relief
WORKDIR /home/Relief
RUN pip install --no-cache-dir -r requirements/prod.txt

COPY ./docker/prod/python/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

RUN useradd relief
RUN usermod -aG users relief
RUN chown -R relief:users /home/Relief && chmod -R 755 /home/Relief
USER relief