name: Deploy to Lightsail

on:
  pull_request:
    types:
      - closed
    branches:
      - master  # or the branch you deploy from

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: relief-env
    env:
      LIGHTSAIL_SSH_KEY: ${{ secrets.LIGHTSAIL_SSH_KEY }}
      LIGHTSAIL_HOST: ${{ secrets.LIGHTSAIL_HOST }}
      LIGHTSAIL_USER: ${{ secrets.LIGHTSAIL_USER }}


    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Echo variables
      run: |
        echo -e "LIGHTSAIL_SSH_KEY::\n"
        echo $LIGHTSAIL_SSH_KEY
        echo -e "LIGHTSAIL_HOST::\n"
        echo $LIGHTSAIL_HOST
        echo -e "LIGHTSAIL_USER::\n"
        echo $LIGHTSAIL_USER
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo $LIGHTSAIL_SSH_KEY > ~/.ssh/gh_rsa
        chmod 600 ~/.ssh/gh_rsa
        ssh-keyscan -H $LIGHTSAIL_HOST >> ~/.ssh/known_hosts

    - name: Deploy via SSH
      run: |
        ssh $LIGHTSAIL_USER@$LIGHTSAIL_HOST << 'EOF'
          NOW=$( date '+%Y%m%d%H%M%S' )
          cd /home/ubuntu/relief-invoice-system  # Adjust this
          docker compose -f docker-compose.prod.yml down -v
          cp /home/ubuntu/relief-invoice-system/relief.sqlite "../db-backup/relief-${NOW}.sqlite"
          git pull origin master
          docker compose -f docker-compose.prod.yml up -d --build
          docker compose -f docker-compose.prod.yml exec web python manage.py migrate --noinput
          docker compose -f docker-compose.prod.yml exec web python manage.py collectstatic --no-input --clear
        EOF
